from django.urls import path
from rest_framework import routers

import pac.rrf.views as views
import pac.rrf.dashboards as dashboards

router = routers.DefaultRouter()

router.register(r'request', views.RequestViewSet, basename='request')

urlpatterns = [
    path('requestinformation/update/',
         views.RequestInformationUpdateView.as_view(),
         name='request-info-update'
         ),
    path(
        'requestinformation/account/<int:account_id>/<int:service_level_id>/',
        views.GetRequestInformationByAccountPyodbcView.as_view(),
        name='request-info-account-get'
    ),
    path(
        'requestinformation/id/<str:request_number>/',
        views.GetRequestInformationByIDPyodbcView.as_view(),
        name='request-info-id-get'
    ),
    path(
        'requestinformation/<str:request_number>/',
        views.RequestInformationRetrieveView.as_view(),
        name='request-info-number-get'
    ),
    path(
        'requestprofile/<str:request_number>/',
        views.RequestProfileRetrieveView.as_view(),
        name='request-profile-number-get'
    ),
    path(
        'requestprofile/<str:request_number>/history/<int:version_num>/',
        views.RequestProfileHistoryRetrieveVersionView.as_view(),
        name='request-profile-number-history-get'
    ),
    path(
        'requestinformation/<str:request_number>/history/<int:version_num>/',
        views.RequestInformationHistoryRetrievePyodbcView.as_view(),
        name='request-information-number-history-get'
    ),
    path(
        'requestprofile/',
        views.RequestProfileUpdateView.as_view(),
        name='request-profile-update'
    ),
    path(
        'request/<int:request_id>/reassign/',
        views.RequestStatusReassignUpdateView.as_view(),
        name='request-reassign'
    ),
    path(
        'request/<int:request_id>/account/',
        views.GetAccountHistoryPyodbcView.as_view(),
        name='request-account-history'
    ),
    path(
        'request/<int:request_id>/tariff/',
        views.GetTariffHistoryPyodbcView.as_view(),
        name='request-tariff-history'
    ),
    path(
        'requestlane/update/',
        views.RequestLaneUpdateView.as_view(),
        name='request-lane-update'
    ),
    path(
        'requestlane/<str:request_number>/history/<int:version_num>/',
        views.RequestLaneHistoryRetrieveVersionView.as_view(),
        name='request-lane-number-history-get'
    ),
    path(
        'requestlane/<str:request_number>/',
        views.RequestLaneRetrieveView.as_view(),
        name='request-lane-get'
    ),
    path(
        'requestsection/',
        views.RequestSectionCreateUpdateDuplicateView.as_view(),
        name='request-section-create-update-duplicate'
    ),
    path(
        'requestsection/<str:request_number>/history/<int:version_num>/',
        views.RequestSectionHistoryListVersionView.as_view(),
        name='request-section-number-history-list'
    ),
    path(
        'requestsection/<str:request_number>/',
        views.RequestSectionListView.as_view(),
        name='request-section-list'
    ),
    path(
        'requestsectionlane/',
        views.RequestSectionLaneListView.as_view(),
        name='request-section-lane-list'
    ),
    path(
        'requestsectionlane/<int:request_section_lane_id>/<str:action_type>/',
        views.RequestSectionLaneListView.as_view(),
        name='request-section-lane-patch'
    ),
    path(
        'requestsectionlane/<str:request_number>/history/<int:version_num>/',
        views.RequestSectionLaneHistoryListVersionView.as_view(),
        name='request-section-lane-number-history-list'
    ),
    path(
        'requestsectionlane/staging/',
        views.RequestSectionLaneStagingListView.as_view(),
        name='request-section-lane-staging-list'
    ),
    path(
        'requestsectionlane/staging/count/<int:request_section_id>/<str:context_id>/',
        views.GetRequestSectionLaneChangeCountPyodbcView.as_view(),
        name='request-section-lane-staging-list'
    ),
    path(
        'requestsectionlane/create/',
        views.CreateRequestSectionLanePyodbcView.as_view(),
        name='request-section-lane-create'
    ),
    path(
        'requestsectionlane/update/',
        views.UpdateRequestSectionLanePyodbcView.as_view(),
        name='request-section-lane-update'
    ),
    path(
        'requestsectionlane/update/request/',
        views.UpdateRequestSectionLaneRequestPyodbcView.as_view(),
        name='request-section-lane-update'
    ),
    path(
        'requestsectionlane/<int:request_section_id>/<str:orig_type>/<int:orig_id>/<str:dest_type>/<int:dest_id>/<str:lane_status>/locationtree/',
        views.GetRequestLaneLocationTreePyodbcView.as_view(),
        name='request-section-lane-location-tree'
    ),
    path(
        'requestsectionlane/staging/<int:request_section_id>/<str:orig_type>/<int:orig_id>/<str:dest_type>/<int:dest_id>/<str:lane_status>/locationtree/',
        views.GetRequestLaneStagingLocationTreePyodbcView.as_view(),
        name='request-section-lane-staging-location-tree'
    ),
    path(
        'requestsectionlane/search/points/<str:group_type>/<int:group_id>/<str:point_type>/<str:point_name>/',
        views.SearchRequestSectionLanePointsPyodbcView.as_view(),
        name='request-section-lane-search-points'
    ),
    # pac-1038
    path(
        'requestsectionlane/<int:request_section_id>/<str:template>/export/',
        views.RequestLaneExportView.as_view(),
        name='request-section-lane-export'
    ),
    # pac-1841
    path(
        'requestsectionlane/<int:request_section_id>/<str:rate_type>/import/',
        views.RequestLaneImportView.as_view(),
        name='request-section-lane-import'
    ),
    path(
        'requestsectionlane/pricingpoint/<int:request_section_id>/<str:rate_type>/import/',
        views.RequestLanePricingPointImportView.as_view(),
        name='request-section-lane-import'
    ),
    path(
        'requestsectionlane/<int:request_section_id>/import/confirm/',
        views.RequestLaneImportConfirmView.as_view(),
        name='request-section-lane-import-confirm'),
    path(
        'requestsectionlane/<int:request_section_id>/import/results/',
        views.ImportResults.as_view(),
        name='request-section-lane-import-results'),
    # path(
    #     'requestsectionlane/<int:request_section_id>/import/confirm/',
    #     views.RequestLaneImportConfirmView.as_view(),
    #     name='request-section-lane-import-confirm'),
    path(
        'requestsectionlane/pricingpoint/<int:request_section_id>/import/confirm/',
        views.RequestLanePricingPointImportConfirmView.as_view(),
        name='request-section-lane-pricingpoint-import-confirm'),
    path(
        'requestsectionlane/<int:request_section_id>/import/cancel/',
        views.RequestLaneImportCancelView.as_view(),
        name='request-section-lane-import-cancel'
    ),
    path(
        'requestsectionlane/<int:request_section_id>/import/status',
        views.RequestLaneImportStatusView.as_view(),
        name='request-section-lane-import-status'
    ),
    path(
        'requestsectionlane/pricingpoint/search/origin/<int:request_section_lane_id>/<str:postal_code>/',
        views.SearchOriginPostalCodesPyodbcView.as_view(),
        name='request-section-lane-pricing-point-search-origin'
    ),
    path(
        'requestsectionlane/pricingpoint/<int:request_section_id>/<str:template>/export/',
        views.RequestLanePricingPointExportView.as_view(),
        name='request-section-lane-pricing-point-export'
    ),
    path(
        'requestsectionlane/pricingpoint/search/destination/<int:request_section_lane_id>/<str:postal_code>/',
        views.SearchDestinationPostalCodesPyodbcView.as_view(),
        name='request-section-lane-pricing-point-search-destination'
    ),
    path(
        'requestsectionlane/pricingpoint/create/',
        views.CreateRequestSectionLanePricingPointPyodbcView.as_view(),
        name='request-section-lane-pricing-point-create'
    ),
    path(
        'requestsectionlane/pricingpoint/<int:request_section_lane_id>/',
        views.GetRequestSectionLanePricingPointsPyodbcView.as_view(),
        name='request-section-lane-pricing-point-get'
    ),
    path(
        'requestsectionlane/pricingpoint/<int:request_section_lane_id>/pricing-point-cost-override/',
        views.PathRequestSectionLanePricingPointCostOverridePyodbcView.as_view(),
        name='request-section-lane-pricing-point-patch'
    ),
    path(
        'requestsectionlane/pricingpoint/<int:request_section_lane_id>/history/<int:version_num>/',
        views.GetRequestSectionLanePricingPointsHistoryPyodbcView.as_view(),
        name='request-section-lane-pricing-point-history-get'
    ),
    path(
        'requestsectionlane/pricingpoint/<int:request_section_lane_id>/staging/<str:context_id>/',
        views.GetRequestSectionLanePricingPointsStagingPyodbcView.as_view(),
        name='request-section-lane-pricing-point-staging-get'
    ),
    path(
        'requestsectionlane/pricingpoint/update/',
        views.UpdateRequestSectionLanePricingPointPyodbcView.as_view(),
        name='request-section-lane-pricing-point-update'
    ),
    path(
        'requestsectionlane/pricingpoint/update/rate/',
        views.UpdateRequestSectionLanePricingPointRatePyodbcView.as_view(),
        name='request-section-lane-pricing-point-update-rate'
    ),

    path(
        'requestsectionlane/pricingpoint/destination/<int:request_section_lane_pricing_point_id>/<int:destination_request_section_id>/',
        views.GetRequestSectionLanePricingPointDestinationPyodbcView.as_view(),
        name='request-section-lane-pricing-point-destination'
    ),
    path(
        'dashboard/header/<int:user_id>/',
        dashboards.GetDashboardRequestHeader.as_view(),
        name='dashboard-header-get'
    ),
    path(
        'dashboard/filter/request/',
        dashboards.RequestFilteredView.as_view(),
        name='dashboard-filter-request'
    ),
    path(
        'dashboard/filter/speedsheet/',
        dashboards.SpeedsheetFilteredView.as_view(),
        name='dashboard-filter-speedsheet'
    ),
    path(
        'request/header/<str:request_number>/<int:user_id>/',
        dashboards.GetRequestHeaderPyodbcView.as_view(),
        name='request-header-get'
    ),
    path(
        'request/header/<str:request_number>/history/<int:version_num>/<int:user_id>/',
        views.GetRequestHeaderHistoryPyodbcView.as_view(),
        name='request-header-get'
    ),
    path(
        'customeraccountsynch/<str:request_number>/<str:account_number>/',
        views.RequestCustomerAccountSynchronizeView.as_view(),
        name='customer-account-synchronize'
    ),
    path(
        'requesteditor/',
        views.RequestStatusRequestEditorRightView.as_view(),
        name='request-editor-rights'
    ),
    path(
        'requesteditor/update/<str:request_id>/',
        views.RequestStatusCurrentEditorUpdateView.as_view(),
        name='request-current-editor-update'
    ),
    path(
        'workflow/',
        views.WorkflowManagerView.as_view(),
        name='workflow-post'
    ),

    path(
        'speed-sheet/',
        views.SpeedsheetPyodbcView.as_view(),
        name='speed-sheet-post-get-list'
    ),
    path(
        'speed-sheet/<str:request_id>/',
        views.SpeedsheetPyodbcView.as_view(),
        name='speed-sheet-get-one'
    ),
    # pac-2263
    path(
        'speed-sheet/export/<str:export_format>/<str:speed_sheet_id>',
        views.SpeedsheetExportPyodbcView.as_view(),
        name='speed-sheet-export'
    ),
    path(
        'speed-sheet/<str:speed_sheet_id>/<str:action_type>',
        views.SpeedsheetModifyPyodbcView.as_view(),
        name='speed-sheet-modify'
    ),
    path(
        'speed-sheet/<str:request_id>/reassign/',
        views.RequestStatusReassignUpdateView.as_view(),
        name='speedsheet-reassign'
    ),
    path(
        'speed-sheet/<str:request_id>/requesteditor/',
        views.RequestStatusRequestEditorRightView.as_view(),
        name='request-editor-rights'
    ),
    path(
        'speed-sheet-profile/',
        views.RequestProfileUpdateView.as_view(),
        name='speed-sheet-profile-update'
    ),
    path(
        'speed-sheet-profile/<str:request_number>/',
        views.RequestProfileRetrieveView.as_view(),
        name='speed-sheet-profile-number-get'
    ),
    path(
        'speed-sheet-profile/requesteditor/update/<str:request_id>/',
        views.RequestStatusCurrentEditorUpdateView.as_view(),
        name='speed-sheet-current-editor-update'
    ),
    path(
        'speed-sheet-profile/<str:request_number>/history/<int:version_num>/',
        views.RequestProfileHistoryRetrieveVersionView.as_view(),
        name='speed-sheet-profile-number-history-get'
    ),
    path(
        'speed-sheet-section-lane/create/',
        views.CreateRequestSectionLanePyodbcView.as_view(),
        name='request-section-lane-create'
    ),
    path('speed-sheet-info/<str:request_number>/update/',
         views.SpeedsheetInformationUpdateView.as_view(),
         name='speed-sheet-update'
         ),
    path(
        'initiate-rrf/',
        views.InitiateRRFView.as_view(),
        name='initiate-rrf'
    ),

]
urlpatterns += router.urls
