# Generated by Django 2.1.13 on 2020-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0006_comment_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.TextField(blank=True, db_column='Meta', default='', null=True),
        ),
    ]
