# Generated by Django 2.1.13 on 2021-03-24 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0008_account_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(db_column='CityID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.City'),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='city_version',
            field=models.ForeignKey(db_column='CityVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.CityHistory'),
        ),
    ]
