# Generated by Django 2.1.13 on 2021-05-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0009_make_account_city_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subservicelevel',
            unique_together={('service_level', 'sub_service_level_name', 'sub_service_level_code')},
        ),
    ]
