# Generated by Django 2.1.13 on 2021-04-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pac', '0009_make_account_city_nullable'),
        ('pre_costing', '0010_auto_20210306_0425'),
    ]

    operations = [
        migrations.AddField(

            model_name='brokercontractcost',
            name='sub_service_level',
            field=models.ForeignKey(db_column='SubServiceLevelID', default=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel'),
        ),
        migrations.AddField(
            model_name='brokercontractcosthistory',
            name='sub_service_level_version',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', default=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory'),
        ),
        migrations.AddField(
            model_name='lane',
            name='sub_service_level',
            field=models.ForeignKey(db_column='SubServiceLevelID', default=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel'),
        ),
        migrations.AddField(
            model_name='lanehistory',
            name='sub_service_level_version',
            field=models.ForeignKey(db_column='SubServiceLevelVersionID', default=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevelHistory'),
        ),
    ]
