# Generated by Django 2.1.13 on 2021-04-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0009_make_account_city_nullable'),
        ('pre_costing', '0011_service_level_to_sub_service_level'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='brokercontractcost',
            index_together={('terminal', 'sub_service_level')},
        ),
        migrations.AlterIndexTogether(
            name='lane',
            index_together={('origin_terminal', 'destination_terminal', 'sub_service_level')},
        ),
    ]
