# # Generated by Django 2.1.13 on 2021-04-21 20:20
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('pre_costing', '0012_alter_indices_lane_broker_contr'),
#     ]
#
#     operations = [
#         migrations.RemoveField(
#             model_name='brokercontractcost',
#             name='service_level',
#         ),
#         migrations.RemoveField(
#             model_name='brokercontractcosthistory',
#             name='service_level_version',
#         ),
#         migrations.RemoveField(
#             model_name='lane',
#             name='service_level',
#         ),
#         migrations.RemoveField(
#             model_name='lanehistory',
#             name='service_level_version',
#         ),
#     ]
