# Generated by Django 2.1.13 on 2020-09-14 22:32

import core.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=True)),
                ('user_id', models.BigAutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='UserName', max_length=50)),
                ('user_email', models.CharField(db_column='UserEmail', max_length=50, unique=True)),
                ('azure_is_active', models.BooleanField(db_column='AzureIsActive', default=True)),
                ('is_away', models.BooleanField(db_column='IsAway', default=False)),
                ('has_self_assign', models.BooleanField(db_column='HasSelfAssign', default=False)),
                ('can_process_scs', models.BooleanField(db_column='CanProcessSCS', default=False)),
                ('can_process_requests', models.BooleanField(db_column='CanProcessRequests', default=False)),
                ('can_process_reviews', models.BooleanField(db_column='CanProcessReviews', default=False)),
                ('azure_id', models.CharField(db_column='AzureID', max_length=36, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'User',
            },
            managers=[
                ('objects', core.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=True)),
                ('persona_id', models.BigAutoField(db_column='PersonaID', primary_key=True, serialize=False)),
                ('persona_name', models.CharField(db_column='PersonaName', max_length=50)),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='PersonaHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=1)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('updated_by', models.CharField(db_column='UpdatedBy', default='', max_length=50)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None, null=True)),
                ('comments', models.CharField(db_column='Comments', default='', max_length=4000)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=True)),
                ('persona_version_id', models.BigAutoField(db_column='PersonaVersionID', primary_key=True, serialize=False)),
                ('persona_name', models.CharField(db_column='PersonaName', max_length=50)),
                ('persona', models.ForeignKey(db_column='PersonaID', on_delete=django.db.models.deletion.CASCADE, to='core.Persona')),
            ],
            options={
                'db_table': 'Persona_History',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('version_num', models.IntegerField(db_column='VersionNum', default=1)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('updated_by', models.CharField(db_column='UpdatedBy', default='', max_length=50)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None, null=True)),
                ('comments', models.CharField(db_column='Comments', default='', max_length=4000)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=True)),
                ('user_version_id', models.BigAutoField(db_column='UserVersionID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='UserName', max_length=50)),
                ('user_email', models.CharField(db_column='UserEmail', max_length=50)),
                ('azure_id', models.CharField(db_column='AzureID', max_length=36, null=True)),
                ('azure_is_active', models.BooleanField(db_column='AzureIsActive', default=True)),
                ('is_away', models.BooleanField(db_column='IsAway', default=False)),
                ('has_self_assign', models.BooleanField(db_column='HasSelfAssign', default=False)),
                ('can_process_scs', models.BooleanField(db_column='CanProcessSCS', default=False)),
                ('can_process_requests', models.BooleanField(db_column='CanProcessRequests', default=False)),
                ('can_process_reviews', models.BooleanField(db_column='CanProcessReviews', default=False)),
                ('persona_version', models.ForeignKey(db_column='PersonaVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PersonaHistory')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_manager_version', models.ForeignKey(db_column='UserManagerVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserHistory')),
            ],
            options={
                'db_table': 'User_History',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='persona',
            field=models.ForeignKey(db_column='PersonaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Persona'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_manager',
            field=models.ForeignKey(db_column='UserManagerID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
