# Generated by Django 2.1.13 on 2020-10-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0002_auto_20201022_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinformation',
            name='extended_payment_terms_margin',
            field=models.FloatField(db_column='ExtendedPaymentTermsMargin', default=True, null=True),
        ),
        migrations.AddField(
            model_name='requestinformationhistory',
            name='extended_payment_terms_margin',
            field=models.FloatField(db_column='ExtendedPaymentTermsMargin', default=True, null=True),
        ),
        migrations.AddIndex(
            model_name='requestsectionhistory',
            index=models.Index(fields=['request_lane_version'], name='IX1'),
        ),
        migrations.AddIndex(
            model_name='requestsectionhistory',
            index=models.Index(fields=['request_lane_version', 'section_number'], name='IX2'),
        ),
        migrations.AddIndex(
            model_name='requestsectionhistory',
            index=models.Index(fields=['request_section'], name='IX3'),
        ),
    ]
