# Generated by Django 2.1.13 on 2020-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0003_auto_20201030_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsection',
            name='as_rating',
            field=models.BooleanField(db_column='AsRating', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='base_rate',
            field=models.BooleanField(db_column='BaseRate', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='has_max',
            field=models.BooleanField(db_column='HasMax', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='has_min',
            field=models.BooleanField(db_column='HasMin', default=True),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='unit_factor',
            field=models.DecimalField(db_column='UnitFactor', decimal_places=6, default=100, max_digits=19),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='weight_break_details',
            field=models.TextField(db_column='WeightBreakDetails', default='[]'),
        ),
    ]
