# Generated by Django 2.1.13 on 2020-11-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0004_auto_20201106_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_accessorials_percentage',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsPercentage', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_accessorials_value',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsValue', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_delivery_cost',
            field=models.TextField(blank=True, db_column='CostOverrideDeliveryCost', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_delivery_count',
            field=models.IntegerField(db_column='CostOverrideDeliveryCount', default=0, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_density',
            field=models.TextField(db_column='CostOverrideDensity', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_dock_adjustment',
            field=models.DecimalField(db_column='CostOverrideDockAdjustment', decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_margin',
            field=models.TextField(db_column='CostOverrideMargin', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_pickup_cost',
            field=models.TextField(blank=True, db_column='CostOverridePickupCost', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost_override_pickup_count',
            field=models.IntegerField(db_column='CostOverridePickupCount', default=0, null=True),
        ),
    ]
