# Generated by Django 2.1.13 on 2020-11-24 21:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrf', '0005_request_section_lane_pricing_point_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('file_name', models.TextField(db_column='FileName')),
                ('record_count', models.IntegerField(db_column='RecordCount')),
                ('uni_status', models.TextField(db_column='UniStatus', default='UNPROCESSED')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ImportFile',
            },
        ),
        migrations.CreateModel(
            name='RequestSectionLaneImportQueue',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('request_section_id', models.TextField(db_column='RequestSectionID', null=True)),
                ('section_name', models.TextField(db_column='SectionName', null=True)),
                ('request_section_lane_id', models.TextField(db_column='RequestSectionLaneID', null=True)),
                ('origin_group_type_name', models.TextField(db_column='OriginGroupTypeName', null=True)),
                ('origin_group_code', models.TextField(db_column='OriginGroupCode', null=True)),
                ('origin_point_type_name', models.TextField(db_column='OriginPointTypeName', null=True)),
                ('origin_point_code', models.TextField(db_column='OriginPointCode', null=True)),
                ('destination_group_type_name', models.TextField(db_column='DestinationGroupTypeName', null=True)),
                ('destination_group_code', models.TextField(db_column='DestinationGroupCode', null=True)),
                ('destination_point_type_name', models.TextField(db_column='DestinationPointTypeName', null=True)),
                ('destination_point_code', models.TextField(db_column='DestinationPointCode', null=True)),
                ('is_between', models.TextField(db_column='IsBetween', null=True)),
                ('weight_break', models.TextField(db_column='WeightBreak', default='[]')),
                ('status_message', models.TextField(db_column='StatusMessage', null=True)),
                ('uni_status', models.TextField(db_column='UniStatus', default='UNPROCESSED')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(db_column='File', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.ImportFile')),
            ],
            options={
                'db_table': 'RequestSectionLaneImportQueue',
            },
        ),
    ]
