# Generated by Django 2.1.13 on 2020-11-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0006_importfile_requestsectionlaneimportqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='request_section_id',
            field=models.TextField(db_column='RequestSectionID', null=True),
        ),
    ]
