# Generated by Django 2.1.13 on 2020-11-25 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0007_importfile_request_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsectionlaneimportqueue',
            name='file',
            field=models.ForeignKey(db_column='File', on_delete=django.db.models.deletion.CASCADE, related_name='ImportFile', to='rrf.ImportFile'),
        ),
    ]
