# Generated by Django 2.1.13 on 2020-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0008_auto_20201125_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlane',
            name='pricing_rates',
            field=models.TextField(db_column='PricingRates', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlane',
            name='workflow_errors',
            field=models.TextField(db_column='WorkflowErrors', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_accessorials_percentage',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsPercentage', default='[]'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_accessorials_value',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsValue', default='[]'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_delivery_cost',
            field=models.TextField(blank=True, db_column='CostOverrideDeliveryCost', default='[]'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_delivery_count',
            field=models.IntegerField(db_column='CostOverrideDeliveryCount', default=0, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_density',
            field=models.TextField(db_column='CostOverrideDensity', default='[]'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_dock_adjustment',
            field=models.DecimalField(db_column='CostOverrideDockAdjustment', decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_margin',
            field=models.TextField(db_column='CostOverrideMargin', default='[]'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_pickup_cost',
            field=models.TextField(blank=True, db_column='CostOverridePickupCost', default='[]'),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='cost_override_pickup_count',
            field=models.IntegerField(db_column='CostOverridePickupCount', default=0, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='pricing_rates',
            field=models.TextField(db_column='PricingRates', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='workflow_errors',
            field=models.TextField(db_column='WorkflowErrors', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='pricing_rates',
            field=models.TextField(db_column='PricingRates', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='workflow_errors',
            field=models.TextField(db_column='WorkflowErrors', default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_accessorials_percentage',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsPercentage', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_accessorials_value',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsValue', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_delivery_cost',
            field=models.TextField(blank=True, db_column='CostOverrideDeliveryCost', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_delivery_count',
            field=models.IntegerField(db_column='CostOverrideDeliveryCount', default=0, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_density',
            field=models.TextField(db_column='CostOverrideDensity', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_dock_adjustment',
            field=models.DecimalField(db_column='CostOverrideDockAdjustment', decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_margin',
            field=models.TextField(db_column='CostOverrideMargin', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_pickup_cost',
            field=models.TextField(blank=True, db_column='CostOverridePickupCost', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost_override_pickup_count',
            field=models.IntegerField(db_column='CostOverridePickupCount', default=0, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='pricing_rates',
            field=models.TextField(db_column='PricingRates', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='workflow_errors',
            field=models.TextField(db_column='WorkflowErrors', default=None, null=True),
        ),
    ]
