# Generated by Django 2.1.13 on 2020-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0009_request_section_lane_and_pp_rate_and_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsectionlane',
            name='cost_override_accessorials_percentage',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsPercentage', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='cost_override_accessorials_value',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsValue', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='cost_override_delivery_cost',
            field=models.TextField(blank=True, db_column='CostOverrideDeliveryCost', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='cost_override_density',
            field=models.TextField(db_column='CostOverrideDensity', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='cost_override_margin',
            field=models.TextField(db_column='CostOverrideMargin', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='cost_override_pickup_cost',
            field=models.TextField(blank=True, db_column='CostOverridePickupCost', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='pricing_rates',
            field=models.TextField(db_column='PricingRates', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='cost_override_accessorials_percentage',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsPercentage', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='cost_override_accessorials_value',
            field=models.TextField(blank=True, db_column='CostOverrideAccessorialsValue', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='cost_override_delivery_cost',
            field=models.TextField(blank=True, db_column='CostOverrideDeliveryCost', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='cost_override_density',
            field=models.TextField(db_column='CostOverrideDensity', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='cost_override_margin',
            field=models.TextField(db_column='CostOverrideMargin', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='cost_override_pickup_cost',
            field=models.TextField(blank=True, db_column='CostOverridePickupCost', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='pricing_rates',
            field=models.TextField(db_column='PricingRates', default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanepricingpoint',
            name='dock_adjustment',
            field=models.DecimalField(db_column='DockAdjustment', decimal_places=6, max_digits=19, null=True),
        ),
    ]
