# Generated by Django 2.1.13 on 2020-12-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0010_cost_override_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='uni_type',
            field=models.TextField(db_column='UniType', default='UNDEFINED'),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='dock_adjustment',
            field=models.DecimalField(db_column='DockAdjustment', decimal_places=6, max_digits=19, null=True),
        ),
    ]
