# Generated by Django 2.1.13 on 2020-12-08 23:36

from django.db import migrations, models

import pac.rrf.models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0011_auto_20201203_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='destination_group_id',
            field=models.TextField(db_column='DestinationGroupId', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='destination_group_type_id',
            field=models.TextField(db_column='DestinationGroupTypeId', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='destination_point_id',
            field=models.TextField(db_column='DestinationPointId', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='destination_point_type_id',
            field=models.TextField(db_column='DestinationPointTypeId', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='orig_group_type_id',
            field=models.TextField(db_column='OriginGroupTypeId', null=True, verbose_name=pac.rrf.models.RequestSectionLanePointType),
        ),
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='origin_group_id',
            field=models.TextField(db_column='OriginGroupId', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='origin_point_id',
            field=models.TextField(db_column='OriginPointId', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlaneimportqueue',
            name='origin_point_type_id',
            field=models.TextField(db_column='OriginPointTypeId', null=True),
        ),
    ]
