# Generated by Django 2.1.13 on 2020-12-02 01:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrf', '0014_requestsectionlaneimportqueue_uni_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSectionLanePricingPointImportQueue',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('request_section_id', models.TextField(db_column='RequestSectionID', null=True)),
                ('section_name', models.TextField(db_column='SectionName', null=True)),
                ('request_section_lane_id', models.TextField(db_column='RequestSectionLaneID', null=True)),
                ('origin_point_code', models.TextField(db_column='OriginPointCode', null=True)),
                ('destination_point_code', models.TextField(db_column='DestinationPointCode', null=True)),
                ('request_section_lane_pricing_point_id', models.TextField(db_column='RequestSectionLanePricingPointID', null=True)),
                ('origin_post_code_id', models.TextField(db_column='OriginPostCodeID', null=True)),
                ('origin_postal_code_name', models.TextField(db_column='OriginPostalCodeName', null=True)),
                ('destination_post_code_id', models.TextField(db_column='DestinationPostCodeID', null=True)),
                ('destination_postal_code_name', models.TextField(db_column='DestinationPostalCodeName', null=True)),
                ('weight_break', models.TextField(db_column='WeightBreak', default='[]')),
                ('status_message', models.TextField(db_column='StatusMessage', null=True)),
                ('uni_status', models.TextField(db_column='UniStatus', default='UNPROCESSED')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(db_column='File', on_delete=django.db.models.deletion.CASCADE, related_name='PricingPointsImportFile', to='rrf.ImportFile')),
            ],
            options={
                'db_table': 'RequestSectionLanePricingPointImportQueue',
            },
        ),
    ]
