# Generated by Django 2.1.13 on 2020-12-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0016_requestsectionlanepricingpointimportqueue_uni_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlanepricingpointimportqueue',
            name='destination_postal_code_id',
            field=models.IntegerField(db_column='DestinationPostalCodeId', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointimportqueue',
            name='origin_postal_code_id',
            field=models.IntegerField(db_column='OriginPostalCodeId', null=True),
        ),
    ]
