# Generated by Django 2.1.13 on 2020-12-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0017_auto_20201215_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsectionlanepricingpointimportqueue',
            name='uni_type',
            field=models.TextField(db_column='UniType', default='UNDEFINED'),
        ),
    ]
