# Generated by Django 2.1.13 on 2020-12-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0018_auto_20201215_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsectionlane',
            name='basing_point_hash_code',
            field=models.BinaryField(db_column='BasingPointHashCode', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlane',
            name='lane_hash_code',
            field=models.BinaryField(db_column='LaneHashCode'),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='basing_point_hash_code',
            field=models.BinaryField(db_column='BasingPointHashCode', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanehistory',
            name='lane_hash_code',
            field=models.BinaryField(db_column='LaneHashCode'),
        ),
        migrations.AlterField(
            model_name='requestsectionlanepricingpoint',
            name='pricing_point_hash_code',
            field=models.BinaryField(db_column='PricingPointHashCode'),
        ),
        migrations.AlterField(
            model_name='requestsectionlanepricingpointhistory',
            name='pricing_point_hash_code',
            field=models.BinaryField(db_column='PricingPointHashCode'),
        ),
        migrations.AlterField(
            model_name='requestsectionlanestaging',
            name='basing_point_hash_code',
            field=models.BinaryField(db_column='BasingPointHashCode', null=True),
        ),
        migrations.AlterField(
            model_name='requestsectionlanestaging',
            name='lane_hash_code',
            field=models.BinaryField(db_column='LaneHashCode'),
        ),
    ]
