# Generated by Django 2.1.13 on 2020-12-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0019_request_hash_codes_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinformation',
            name='speedsheet_name',
            field=models.TextField(blank=True, db_column='SpeedsheetName', null=True),
        ),
        migrations.AddField(
            model_name='requestinformation',
            name='uni_type',
            field=models.TextField(db_column='UniType', null=True),
        ),
    ]
