# Generated by Django 2.1.13 on 2021-01-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0021_request_request_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlane',
            name='is_excluded',
            field=models.BooleanField(db_column='IsExcluded', default=False, null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanehistory',
            name='is_excluded',
            field=models.BooleanField(db_column='IsExcluded', default=False, null=True),
        ),
    ]
