# Generated by Django 2.1.13 on 2021-01-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0022_auto_20210102_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='speedsheet_name',
            field=models.TextField(blank=True, db_column='SpeedsheetName', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='uni_type',
            field=models.TextField(db_column='UniType', null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='speedsheet_name',
            field=models.TextField(blank=True, db_column='SpeedsheetName', null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='uni_type',
            field=models.TextField(db_column='UniType', null=True),
        ),
        migrations.RemoveField(
            model_name='requestinformation',
            name='speedsheet_name',
        ),
        migrations.RemoveField(
            model_name='requestinformation',
            name='uni_type',
        ),
    ]
