# Generated by Django 2.1.13 on 2021-01-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0023_speed_sheet_amendments'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlanepricingpoint',
            name='cost',
            field=models.TextField(db_column='Cost', default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestsectionlanepricingpointhistory',
            name='cost',
            field=models.TextField(db_column='Cost', default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestsectionlanepricingpointhistory',
            name='dock_adjustment',
            field=models.DecimalField(db_column='DockAdjustment', decimal_places=6, max_digits=19, null=True),
        ),
    ]
