# Generated by Django 2.1.13 on 2021-01-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0024_request_section_pricing_ponts_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratebase',
            name='description',
            field=models.TextField(db_column='Description', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratebase',
            name='effective_date',
            field=models.DateField(db_column='EffectiveDate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratebase',
            name='product_number',
            field=models.CharField(db_column='ProductNumber', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratebase',
            name='release',
            field=models.IntegerField(db_column='Release', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratebasehistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratebasehistory',
            name='effective_date',
            field=models.DateField(db_column='EffectiveDate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratebasehistory',
            name='product_number',
            field=models.CharField(db_column='ProductNumber', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ratebasehistory',
            name='release',
            field=models.IntegerField(db_column='Release', max_length=50, null=True),
        ),
    ]
