# Generated by Django 2.1.13 on 2021-02-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0025_rate_base_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratebase',
            name='release',
            field=models.CharField(db_column='Release', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratebasehistory',
            name='release',
            field=models.CharField(db_column='Release', max_length=50, null=True),
        ),
        
    ]
