# Generated by Django 2.1.13 on 2021-02-10 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0026_rate_base_release_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='language',
            field=models.ForeignKey(db_column='LanguageID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.Language'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='language',
            field=models.ForeignKey(db_column='LanguageID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrf.Language'),
        ),
    ]
