# Generated by Django 2.1.13 on 2021-02-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0028_auto_20210218_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinformation',
            name='effective_date',
            field=models.DateField(db_column='EffectiveDate', null=True),
        ),
        migrations.AddField(
            model_name='requestinformation',
            name='expiry_date',
            field=models.DateField(db_column='ExpiryDate', null=True),
        ),
        migrations.AddField(
            model_name='requestinformationhistory',
            name='effective_date',
            field=models.DateField(db_column='EffectiveDate', null=True),
        ),
        migrations.AddField(
            model_name='requestinformationhistory',
            name='expiry_date',
            field=models.DateField(db_column='ExpiryDate', null=True),
        ),
    ]
