# Generated by Django 2.1.13 on 2021-02-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0029_requestinfo_effective_and_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlanestaging',
            name='pricing_rates',
            field=models.TextField(db_column='PricingRates', default='[]', null=True),
        ),
        migrations.AddField(
            model_name='requestsectionlanestaging',
            name='workflow_errors',
            field=models.TextField(db_column='WorkflowErrors', default=None, null=True),
        ),
    ]
