# Generated by Django 2.1.13 on 2021-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0030_auto_20210228_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='between_lane_count',
            field=models.IntegerField(db_column='BetweenLaneCount', default=0),
        ),
        migrations.AddField(
            model_name='importfile',
            name='directional_lane_count',
            field=models.IntegerField(db_column='DirectionalLaneCount', default=0),
        ),
        migrations.AddField(
            model_name='importfile',
            name='duplicate_lane_count',
            field=models.IntegerField(db_column='DuplicateLaneCount', default=0),
        ),
    ]
