# Generated by Django 2.1.13 on 2022-03-18 14:31

from django.db import migrations

# Method to add new RequestStatusTypes required for PAC 2402
def add_status_types(apps, schema_editor):

    RequestStatusType = apps.get_model('rrf', 'RequestStatusType')

    field_names = ('request_status_type_name', 'is_active', 'is_inactive_viewable', 'next_request_status_type',
                    'assigned_persona', 'editor', 'queue_personas', 'is_secondary', 'is_final')

    new_request_status_type_data = [
        ('D&R RRF Initiated', 1, 1, '["D&R RRF with Pricing"]', 'Pricing Manager', 'Pricing Manager',
         '["Pricing Manager"]', 0, 0),
        ('D&R RRF with Pricing', 1, 1, '["D&R RRF Published","D&R RRF Archived", "D&R RRF Cancelled"]',
         'Pricing Manager', 'Pricing Manager', '["Pricing Manager","Pricing Analyst"]', 0, 0),
        ('D&R RRF Archived', 1, 1, '[]', 'Pricing Manager', 'Pricing Manager', '["Pricing Manager","Pricing Analyst"]',
         0, 0),
        ('D&R RRF Cancelled', 1, 1, '["D&R RRF with Pricing"]', 'Pricing Manager', 'Pricing Manager',
         '["Pricing Manager","Pricing Analyst"]', 0, 0),
        ('D&R RRF Reinitiated', 1, 1, '["D&R RRF with Pricing"]', 'Pricing Manager', 'Pricing Manager',
         '["Pricing Manager","Pricing Analyst"]', 0, 0),
        ('D&R RRF Published', 1, 1, '[]', 'Pricing Manager', 'Pricing Manager', '["Pricing Manager","Pricing Analyst"]',
         0, 0)
    ]

    # Create RequestStatusTypes
    request_status_types = [RequestStatusType(**dict(zip(field_names, d))) for d in new_request_status_type_data]

    # insert data
    RequestStatusType.objects.bulk_create(request_status_types)


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0031_auto_20210318_1642'),
    ]

    operations = [
        migrations.RunPython(add_status_types)
    ]
