# Generated by Django 2.1.13 on 2022-04-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0010_auto_20210520_2039'),
        ('rrf', '0033_auto_20220405_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerZones',
            fields=[
                ('customer_zone_id', models.BigAutoField(db_column='CustomerZoneID', max_length=8, primary_key=True, serialize=False)),
                ('customer_zone_name', models.TextField(db_column='CustomerZoneName', max_length=40, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('service_point_id', models.ForeignKey(db_column='ServicePointID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.ServicePoint')),
            ],
            options={
                'db_table': 'CustomerZones',
            },
        ),
        migrations.CreateModel(
            name='CustomerZonesHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=False)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=False)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=False)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=False)),
                ('comments', models.TextField(db_column='Comments', default=False)),
                ('customer_zone_version_id', models.BigAutoField(db_column='CustomerZoneVersionID', primary_key=True, serialize=False)),
                ('customer_zone_name', models.TextField(db_column='CustomerZoneName', max_length=40, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('customer_zone_id', models.ForeignKey(db_column='CustomerZoneID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rrf.CustomerZones')),
                ('service_point_version_id', models.ForeignKey(db_column='ServicePointVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.ServicePointHistory')),
            ],
            options={
                'db_table': 'CustomerZonesHistory',
            },
        ),
        migrations.CreateModel(
            name='SubPostalCode',
            fields=[
                ('sub_postal_code_id', models.BigAutoField(db_column='SubPostalCodeID', max_length=8, primary_key=True, serialize=False)),
                ('sub_postal_code_name', models.TextField(db_column='SubPostalCodeName', max_length=40, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('postal_code_id', models.ForeignKey(db_column='PostalCodeID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.PostalCode')),
            ],
            options={
                'db_table': 'SubPostalCode',
            },
        ),
        migrations.CreateModel(
            name='SubPostalCodeHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=False)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn', default=False)),
                ('updated_by', models.TextField(db_column='UpdatedBy', default=False)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=False)),
                ('comments', models.TextField(db_column='Comments', default=False)),
                ('sub_postal_code_version_id', models.BigAutoField(db_column='SubPostalCodeVersionID', max_length=8, primary_key=True, serialize=False)),
                ('sub_postal_code_name', models.TextField(db_column='SubPostalCodeName', max_length=40, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=False)),
                ('postal_code_version_id', models.ForeignKey(db_column='PostalCodeVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pac.PostalCodeHistory')),
                ('sub_postal_code_id', models.ForeignKey(db_column='SubPostalCodeID', on_delete=django.db.models.deletion.CASCADE, to='rrf.SubPostalCode')),
            ],
            options={
                'db_table': 'SubPostalCodeHistory',
            },
        ),        
        migrations.AlterIndexTogether(
            name='subpostalcodehistory',
            index_together={('sub_postal_code_version_id', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='customerzoneshistory',
            index_together={('customer_zone_version_id', 'version_num')},
        ),
    ]
