# Generated by Django 2.1.13 on 2022-04-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0034_auto_20220405_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(db_column='Description', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_code',
            field=models.CharField(db_column='ZoneCode', default='Test', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zonehistory',
            name='description',
            field=models.TextField(db_column='Description', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zonehistory',
            name='zone_code',
            field=models.CharField(db_column='ZoneCode', default='Test', max_length=10, null=True),
        ),
    ]
