# Generated by Django 2.1.13 on 2022-04-07 18:47

from django.db import migrations,models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0036_auto_20220407_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicematrix',
            name='country_id',
            field=models.ForeignKey(db_column='CountryID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pac.Country'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='postal_code_id',
            field=models.ForeignKey(db_column='PostalCodeID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pac.PostalCode'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='province_id',
            field=models.ForeignKey(db_column='ProvinceID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pac.Province'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='region_id',
            field=models.ForeignKey(db_column='RegionID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pac.Region'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='service_point_id',
            field=models.ForeignKey(db_column='ServicePointID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pac.ServicePoint'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='service_type_id',
            field=models.ForeignKey(db_column='ServiceTypeID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='rrf.ServiceType'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='sub_service_level_id',
            field=models.ForeignKey(db_column='SubServiceLevelID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='terminal_id',
            field=models.ForeignKey(db_column='TerminalID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pac.Terminal'),
        ),
        migrations.AlterField(
            model_name='servicematrix',
            name='zone_id',
            field=models.ForeignKey(db_column='ZoneID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='rrf.Zone'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='country_version_id',
            field=models.ForeignKey(db_column='CountryVersionID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.CountryHistory'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='postal_code_version_id',
            field=models.ForeignKey(db_column='PostalCodeVersionID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.PostalCodeHistory'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='province_version_id',
            field=models.ForeignKey(db_column='ProvinceVersionID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.ProvinceHistory'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='region_version_id',
            field=models.ForeignKey(db_column='RegionVersionID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pac.RegionHistory'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='service_point_version_id',
            field=models.ForeignKey(db_column='ServicePointVersionID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.ServicePointHistory'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='service_type_version_id',
            field=models.ForeignKey(db_column='ServiceTypeVersionID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='rrf.ServiceTypeHistory'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='sub_service_level_id',
            field=models.ForeignKey(db_column='SubServiceLevelID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.SubServiceLevel'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='terminal_version_id',
            field=models.ForeignKey(db_column='TerminalVersionID', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pac.TerminalHistory'),
        ),
        migrations.AlterField(
            model_name='servicematrixhistory',
            name='zone_version_id',
            field=models.ForeignKey(db_column='ZoneVersionID', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='rrf.ZoneHistory'),
        ),
    ]
