# Generated by Django 2.1.13 on 2022-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0037_auto_20220407_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsectionlane',
            name='is_flagged',
            field=models.BooleanField(db_column='IsFlagged', default=False, null=True),
        ),
    ]
