# Generated by Django 2.1.13 on 2022-04-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0039_auto_20220408_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicematrixhistory',
            name='service_matrix',
            field=models.ForeignKey(db_column='ServiceMatrixID', on_delete=django.db.models.deletion.CASCADE, to='rrf.ServiceMatrix'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='servicematrixhistory',
            index_together={('service_matrix', 'version_num')},
        ),
        migrations.AlterIndexTogether(
            name='servicetypehistory',
            index_together={('service_type', 'version_num')},
        ),
    ]
