# Generated by Django 2.1.13 on 2022-04-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrf', '0036_auto_20220407_2126'),
        ('rrf', '0040_auto_20220408_1038'),
    ]

    operations = [
    ]
