IF NOT EXISTS (SELECT *
FROM sys.types
WHERE is_table_type = 1 AND name = 'RequestSectionLaneTableType')
BEGIN
CREATE TYPE [dbo].[RequestSectionLaneTableType] AS TABLE
(
	[IsActive] BIT NOT NULL,
    [IsInactiveViewable] BIT NOT NULL,
	[RequestSectionID]          BIGINT        NOT NULL,
    [LaneNumber]        NVARCHAR(32) NOT NULL,
	[IsPublished]        BIT NOT NULL,
	[IsEdited]        BIT NOT NULL,
	[IsDuplicate]        BIT NOT NULL,
	[IsBetween]        BIT NOT NULL,
	[IsLaneGroup]        BIT NOT NULL,
	[OriginProvinceID] BIGINT NULL,
	[OriginProvinceCode] NVARCHAR(2) NULL,
	[OriginRegionID] BIGINT NULL,
	[OriginRegionCode] NVARCHAR(4) NULL,
	[OriginCountryID] BIGINT NULL,
	[OriginCountryCode] NVARCHAR(2) NULL,
	[OriginTerminalID] BIGINT NULL,
	[OriginTerminalCode] NVARCHAR(3) NULL,
	[OriginZoneID] BIGINT NULL,
	[OriginZoneName] NVARCHAR(50) NULL,
	[OriginBasingPointID] BIGINT NULL,
	[OriginBasingPointName] NVARCHAR(50) NULL,
	[OriginServicePointID] BIGINT NULL,
	[OriginServicePointName] NVARCHAR(50) NULL,
	[OriginPostalCodeID] BIGINT NULL,
	[OriginPostalCodeName] NVARCHAR(10) NULL,
	[OriginPointTypeID] BIGINT NOT NULL,
	[OriginPointTypeName] NVARCHAR(50) NOT NULL,
	[OriginCode] NVARCHAR(50) NOT NULL,
	[DestinationProvinceID] BIGINT NULL,
	[DestinationProvinceCode] NVARCHAR(2) NULL,
	[DestinationRegionID] BIGINT NULL,
	[DestinationRegionCode] NVARCHAR(4) NULL,
	[DestinationCountryID] BIGINT NULL,
	[DestinationCountryCode] NVARCHAR(2) NULL,
	[DestinationTerminalID] BIGINT NULL,
	[DestinationTerminalCode] NVARCHAR(3) NULL,
	[DestinationZoneID] BIGINT NULL,
	[DestinationZoneName] NVARCHAR(50) NULL,
	[DestinationBasingPointID] BIGINT NULL,
	[DestinationBasingPointName] NVARCHAR(50) NULL,
	[DestinationServicePointID] BIGINT NULL,
	[DestinationServicePointName] NVARCHAR(50) NULL,
	[DestinationPostalCodeID] BIGINT NULL,
	[DestinationPostalCodeName] NVARCHAR(10) NULL,
	[DestinationPointTypeID] BIGINT NOT NULL,
	[DestinationPointTypeName] NVARCHAR(50) NOT NULL,
	[DestinationCode] NVARCHAR(50) NOT NULL,
	[LaneHashCode] VARBINARY(8000) NOT NULL,
	[BasingPointHashCode] VARBINARY(8000) NULL,
	[Cost]        NVARCHAR(MAX) NULL,
	[DoNotMeetCommitment] BIT NOT NULL,
	[Commitment] NVARCHAR(MAX) NULL,
	[CustomerRate] NVARCHAR(MAX) NOT NULL,
	[CustomerDiscount] NVARCHAR(MAX) NOT NULL,
	[DrRate] NVARCHAR(MAX) NOT NULL,
	[PartnerRate] NVARCHAR(MAX) NOT NULL,
	[PartnerDiscount] NVARCHAR(MAX) NOT NULL,
	[Profitability] NVARCHAR(MAX) NOT NULL,
	[PickupCount] INT NULL,
	[DeliveryCount] INT NULL,
	[DockAdjustment] DECIMAL(19,6) NULL,
	[Margin] NVARCHAR(MAX) NOT NULL,
	[Density] NVARCHAR(MAX) NOT NULL,
	[PickupCost] NVARCHAR(MAX) NOT NULL,
	[DeliveryCost] NVARCHAR(MAX) NOT NULL,
	[AccessorialsValue] NVARCHAR(MAX) NOT NULL,
	[AccessorialsPercentage] NVARCHAR(MAX) NOT NULL,
	[RequestSectionLaneID]          BIGINT    NULL,
	[NewRequestSectionLaneID]          BIGINT    NULL,
	INDEX IX1 NONCLUSTERED([DestinationPostalCodeID] ASC),
	INDEX IX2 NONCLUSTERED([DestinationServicePointID] ASC),
	INDEX IX3 NONCLUSTERED([DestinationBasingPointID] ASC),
	INDEX IX4 NONCLUSTERED([DestinationZoneID] ASC),
	INDEX IX5 NONCLUSTERED([DestinationTerminalID] ASC),
	INDEX IX6 NONCLUSTERED([DestinationCountryID] ASC),
	INDEX IX7 NONCLUSTERED([DestinationRegionID] ASC),
	INDEX IX8 NONCLUSTERED([DestinationProvinceID] ASC),
	INDEX IX9 NONCLUSTERED([OriginPostalCodeID] ASC),
	INDEX IX10 NONCLUSTERED([OriginServicePointID] ASC),
	INDEX IX11 NONCLUSTERED([OriginBasingPointID] ASC),
	INDEX IX12 NONCLUSTERED([OriginZoneID] ASC),
	INDEX IX13 NONCLUSTERED([OriginTerminalID] ASC),
	INDEX IX14 NONCLUSTERED([OriginCountryID] ASC),
	INDEX IX15 NONCLUSTERED([OriginRegionID] ASC),
	INDEX IX16 NONCLUSTERED([OriginProvinceID] ASC)
)
END




