"""
Django settings for pac project.

Generated by 'django-admin startproject' using Django 2.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# from pac.blobs.utils import BlobFileUploadHandler

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*+%a(n%k&u361f=o@h6q&bnbn*4)!5l^9v(@lxk1f_*m-4u!w7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_swagger',
    'corsheaders',
    'django_filters',
    'core',
    'pac',
    'pac.pre_costing',
    'pac.rrf',
    'azure'

]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'pac.urls'

CORS_ORIGIN_ALLOW_ALL = True  # If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect
CORS_ORIGIN_WHITELIST = [  # TODO keep this for future configuration
    'http://localhost:30662',
]  # If this is used, then not need to use `CORS_ORIGIN_ALLOW_ALL = True`
CORS_ORIGIN_REGEX_WHITELIST = [
    'http://localhost:3030',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pac.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': os.getenv('PAC_DB_NAME'),
        'USER': os.getenv('PAC_DB_USER'),
        'PASSWORD': os.getenv('PAC_DB_PASSWORD'),
        'HOST': os.getenv('PAC_DB_HOST'),
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

#
# NAME': os.getenv('AZURE_UAT_MSSQL_DB_NAME'),
#         'USER': os.getenv('AZURE_UAT_MSSQL_USERNAME'),
#         'PASSWORD': os.getenv('AZURE_UAT_MSSQL_PASSWORD'),
#         'HOST': os.getenv('AZURE_UAT_MSSQL_HOST'),
#         'PORT': os.getenv('AZURE_UAT_MSSQL_PORT'),

DATABASE_CONNECTION_POOLING = False

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/f

STATIC_URL = '/static/'

CPU_COUNT = os.cpu_count() or 1

REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'core.authentication.AzureActiveDirectoryAuthentication',
    # ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    #     # 'core.permissions.IsAuthorized',
    # ],
    # # 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

RATEWARE_USERNAME = os.getenv("RATEWARE_USERNAME")

RATEWARE_PASSWORD = os.getenv("RATEWARE_PASSWORD")

RATEWARE_LICENSE_KEY = os.getenv("RATEWARE_LICENSE_KEY")

RATEWARE_HEADER = {"AuthenticationToken": {"username": RATEWARE_USERNAME,
                                           "password": RATEWARE_PASSWORD, "licenseKey": RATEWARE_LICENSE_KEY}}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'AzureActiveDirectoryAuthentication': {
            'type': 'apiKey',
            'name': 'X-CSRFToken',
            'in': 'header',
        }
    }
}

AUTH_USER_MODEL = 'core.User'

# List of upload handler classes to be applied in order.
# FILE_UPLOAD_HANDLERS = [
#     'pac.blobs.utils.BlobFileUploadHandler'
# ]

FILE_UPLOAD_HANDLERS = [

    "django.core.files.uploadhandler.TemporaryFileUploadHandler"
]
# "django.core.files.uploadhandler.MemoryFileUploadHandler",
DEFAULT_FILE_STORAGE = 'pac.blobs.azure_storage.AzureStorage'
STATIC_LOCATION = '8334f9db-e4c1-43d7-8f4c-87f63abdb1f5'
AZURE_SSL = True
AZURE_CONTAINER = os.getenv("AZURE_CONTAINER")
AZURE_CONTAINER_URL = os.getenv("AZURE_CONTAINER_URL")
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
