# Generated by Django 2.1.13 on 2020-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0002_auto_20201027_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockroute',
            name='is_exclude_destination',
            field=models.BooleanField(db_column='IsExcludeDestination', default=False),
        ),
        migrations.AlterField(
            model_name='dockroute',
            name='is_exclude_source',
            field=models.BooleanField(db_column='IsExcludeSource', default=False),
        ),
    ]
