# Generated by Django 2.1.13 on 2021-02-25 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0007_notification_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pre_costing', '0003_auto_20201030_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='GriReview',
            fields=[
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=True)),
                ('gri_review_id', models.BigAutoField(db_column='GriReviewID', primary_key=True, serialize=False)),
                ('expiry_on', models.DateTimeField(db_column='ExpiryOn', null=True)),
                ('start_on', models.DateTimeField(db_column='StartOn', null=True)),
                ('uni_status', models.TextField(db_column='UniStatus', default='NEW')),
                ('gri_amount', models.FloatField(db_column='GriAmount', default=False, null=True)),
                ('gri_percentage', models.FloatField(db_column='GriPercentage', default=False, null=True)),
                ('min_revenue', models.FloatField(db_column='MinRevenue', default=False, null=True)),
                ('max_revenue', models.FloatField(db_column='MaxRevenue', default=False, null=True)),
                ('min_operating_ratio', models.FloatField(db_column='MinOperatingRatio', default=False, null=True)),
                ('max_operating_ratio', models.FloatField(db_column='MaxOperatingRatio', default=False, null=True)),
                ('current_rate_base', models.CharField(db_column='CurrentRateBase', max_length=100, null=True)),
                ('current_effective_date', models.DateTimeField(db_column='CurrentEffectiveDate', null=True)),
                ('current_tm_ratebase', models.DateTimeField(db_column='CurrentTmRatebase', null=True)),
                ('future_rate_base', models.CharField(db_column='FutureRateBase', max_length=100, null=True)),
                ('future_effective_date', models.DateTimeField(db_column='FutureEffectiveDate', null=True)),
                ('future_tm_ratebase', models.DateTimeField(db_column='FutureTmRatebase', null=True)),
                ('new_effective_date', models.DateTimeField(db_column='NewEffectiveDate', null=True)),
                ('new_expiry_date', models.DateTimeField(db_column='NewExpiryDate', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_level', models.ForeignKey(db_column='ServiceLevelID', on_delete=django.db.models.deletion.CASCADE, to='pac.ServiceLevel')),
            ],
            options={
                'db_table': 'GriReview',
            },
        ),
        migrations.CreateModel(
            name='GriReviewHistory',
            fields=[
                ('version_num', models.IntegerField(db_column='VersionNum', default=1)),
                ('is_latest_version', models.BooleanField(db_column='IsLatestVersion', default=True)),
                ('updated_by', models.CharField(db_column='UpdatedBy', default='', max_length=50)),
                ('base_version', models.IntegerField(db_column='BaseVersion', default=None, null=True)),
                ('comments', models.CharField(db_column='Comments', default='', max_length=4000)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_inactive_viewable', models.BooleanField(db_column='IsInactiveViewable', default=True)),
                ('gri_review_version_id', models.BigAutoField(db_column='GriReviewVersionID', primary_key=True, serialize=False)),
                ('expiry_on', models.DateTimeField(auto_now_add=True, db_column='ExpiryOn', null=True)),
                ('start_on', models.DateTimeField(auto_now_add=True, db_column='StartOn', null=True)),
                ('uni_status', models.TextField(db_column='UniStatus', default='NEW')),
                ('gri_amount', models.FloatField(db_column='GriAmount', default=True, null=True)),
                ('gri_percentage', models.FloatField(db_column='GriPercentage', default=True, null=True)),
                ('min_revenue', models.FloatField(db_column='MinRevenue', default=True, null=True)),
                ('max_revenue', models.FloatField(db_column='MaxRevenue', default=True, null=True)),
                ('min_operating_ratio', models.FloatField(db_column='MinOperatingRatio', default=True, null=True)),
                ('max_operating_ratio', models.FloatField(db_column='MaxOperatingRatio', default=True, null=True)),
                ('current_rate_base', models.CharField(db_column='CurrentRateBase', max_length=100, null=True)),
                ('current_effective_date', models.DateTimeField(auto_now_add=True, db_column='CurrentEffectiveDate', null=True)),
                ('current_tm_ratebase', models.DateTimeField(auto_now_add=True, db_column='CurrentTmRatebase', null=True)),
                ('future_rate_base', models.CharField(db_column='FutureRateBase', max_length=100, null=True)),
                ('future_effective_date', models.DateTimeField(auto_now_add=True, db_column='FutureEffectiveDate', null=True)),
                ('future_tm_ratebase', models.DateTimeField(auto_now_add=True, db_column='FutureTmRatebase', null=True)),
                ('new_effective_date', models.DateTimeField(auto_now_add=True, db_column='NewEffectiveDate', null=True)),
                ('new_expiry_date', models.DateTimeField(auto_now_add=True, db_column='NewExpiryDate', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_column='UpdatedOn')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gri_review', models.ForeignKey(db_column='GriReviewID', on_delete=django.db.models.deletion.CASCADE, to='pre_costing.GriReview')),
                ('service_level', models.ForeignKey(db_column='ServiceLevelID', on_delete=django.db.models.deletion.CASCADE, to='pac.ServiceLevel')),
            ],
            options={
                'db_table': 'GriReviewHistory',
            },
        ),
    ]
