# Generated by Django 2.1.13 on 2021-03-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0005_grireview_ddl_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grireviewhistory',
            name='service_level',
            field=models.ForeignKey(db_column='ServiceLevelID', null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.ServiceLevel'),
        ),
    ]
