# Generated by Django 2.1.13 on 2021-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0006_auto_20210301_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grireview',
            name='current_tm_ratebase',
            field=models.CharField(db_column='CurrentTmRatebase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='future_tm_ratebase',
            field=models.CharField(db_column='FutureTmRatebase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireviewhistory',
            name='current_tm_ratebase',
            field=models.CharField(db_column='CurrentTmRatebase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireviewhistory',
            name='future_tm_ratebase',
            field=models.CharField(db_column='FutureTmRatebase', max_length=100, null=True),
        ),
    ]
