# Generated by Django 2.1.13 on 2021-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0007_alter_grireview_table_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grireview',
            name='current_tm_ratebase',
            field=models.CharField(blank=True, db_column='CurrentTmRatebase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='future_tm_ratebase',
            field=models.CharField(blank=True, db_column='FutureTmRatebase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireviewhistory',
            name='current_tm_ratebase',
            field=models.CharField(blank=True, db_column='CurrentTmRatebase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireviewhistory',
            name='future_tm_ratebase',
            field=models.CharField(blank=True, db_column='FutureTmRatebase', max_length=100, null=True),
        ),
    ]
