# Generated by Django 2.1.13 on 2021-03-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0008_grireview_table_make_fields_blankable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grireview',
            name='current_effective_date',
            field=models.DateTimeField(blank=True, db_column='CurrentEffectiveDate', null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='current_rate_base',
            field=models.CharField(blank=True, db_column='CurrentRateBase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='expiry_on',
            field=models.DateTimeField(blank=True, db_column='ExpiryOn', null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='future_effective_date',
            field=models.DateTimeField(blank=True, db_column='FutureEffectiveDate', null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='future_rate_base',
            field=models.CharField(blank=True, db_column='FutureRateBase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='gri_amount',
            field=models.FloatField(db_column='GriAmount', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='new_effective_date',
            field=models.DateTimeField(blank=True, db_column='NewEffectiveDate', null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='new_expiry_date',
            field=models.DateTimeField(blank=True, db_column='NewExpiryDate', null=True),
        ),
        migrations.AlterField(
            model_name='grireview',
            name='start_on',
            field=models.DateTimeField(blank=True, db_column='StartOn', null=True),
        ),
        migrations.AlterField(
            model_name='grireviewhistory',
            name='current_rate_base',
            field=models.CharField(blank=True, db_column='CurrentRateBase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grireviewhistory',
            name='future_rate_base',
            field=models.CharField(blank=True, db_column='FutureRateBase', max_length=100, null=True),
        ),
    ]
