# Generated by Django 2.1.13 on 2021-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_costing', '0009_auto_20210302_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grireview',
            name='gri_amount',
            field=models.FloatField(db_column='GriAmount', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grireviewhistory',
            name='gri_amount',
            field=models.FloatField(db_column='GriAmount', default=0, null=True),
        ),
    ]
